services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      NODE_ENV: production
      PORT: 3000
      POSTGRES_DATABASE: study
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: study
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
