services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      NODE_ENV: production
      PORT: 3000
      POSTGRES_DATABASE: study
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      # redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: study
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  pg_data:
  redis_data:
