export const products = [
  {
    id: 1,
    name: "Notebook Lenovo IdeaPad",
    category: "electronics",
    price: 3500,
    stock: 8,
    tags: ["computer", "work", "portable"],
  },
  {
    id: 2,
    name: "Mouse Logitech",
    category: "electronics",
    price: 120,
    stock: 25,
    tags: ["accessory", "computer"],
  },
  {
    id: 3,
    name: "Teclado Mecânico",
    category: "electronics",
    price: 280,
    stock: 12,
    tags: ["accessory", "computer", "gaming"],
  },
  {
    id: 4,
    name: "Cadeira Ergonômica",
    category: "furniture",
    price: 900,
    stock: 5,
    tags: ["office", "comfort"],
  },
  {
    id: 5,
    name: "Mesa de Escritório",
    category: "furniture",
    price: 750,
    stock: 3,
    tags: ["office", "wood"],
  },
  {
    id: 6,
    name: "Copo Térmico",
    category: "kitchen",
    price: 80,
    stock: 0,
    tags: ["drink", "thermal"],
  },
];
